server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: purchase-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/purchases/**
         
          filters:
            - StripPrefix=0

        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/games/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
