server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: purchase-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/purchases/**
          filters:
            - StripPrefix=1
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
