server:
  port: 8085

spring:
  application:
    name: game-service
  datasource:
    #url: jdbc:postgresql://localhost:5432/gamedb
    ujdbc:postgresql://postgres-game:5432/gamedb
    username: game_user
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  charset:
    console: UTF-8
    file: UTF-8


custom:
  greeting: "Hello from Game Service"
