server:
  port: 8085

spring:
  application:
    name: game-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gamedb
    username: game_user
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # создаёт/обновляет таблицы автоматически
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

custom:
  greeting: "Hello from Game Service"
