server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: order
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  greeting: "Hello from Order Service"
