server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/productsdb
    username: product
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  greeting: "Hello from Product Service"
