server:
  port: 8083

spring:
  application:
    name: purchase-service

  datasource:
    url: jdbc:postgresql://localhost:5432/purchasedb
    username: purchase_user
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true    

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

custom:
  greeting: "Hello from Purchase Service"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED       # окно ошибок по количеству запросов
        slidingWindowSize: 10                # размер окна (10 запросов)
        minimumNumberOfCalls: 5              # минимальное число вызовов для оценки
        failureRateThreshold: 50             # % ошибок для открытия
        waitDurationInOpenState: 10s         # сколько держать "открытым" перед half-open
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 3s        # порог "медленного вызова"
        slowCallRateThreshold: 50
    instances:
      userService:
        baseConfig: default
      gameService:
        baseConfig: default