server:
  port: 8083

spring:
  application:
    name: purchase-service

  datasource:
    url: jdbc:postgresql://localhost:5432/purchasedb
    username: purchase_user
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true    

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  charset:
    console: UTF-8
    file: UTF-8


custom:
  greeting: "Hello from Purchase Service"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED       
        slidingWindowSize: 10                
        minimumNumberOfCalls: 5              
        failureRateThreshold: 50             
        waitDurationInOpenState: 10s         
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 3s        
        slowCallRateThreshold: 50
    instances:
      userService:
        baseConfig: default
      gameService:
        baseConfig: default