server:
  port: 8084

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: steam_user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  greeting: "Hello from User Service"
