server:
  port: 8084

spring:
  application:
    name: user-service

  datasource:
    #url: jdbc:postgresql://localhost:5432/userdb?currentSchema=public
    url: jdbc:postgresql://user-db:5432/userdb
    username: steam_user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
    open-in-view: false          

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

custom:
  greeting: "Hello from User Service"
